services:
  postgres:
    image: postgres:16.4-alpine
    container_name: next_saas_starter_postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "54322:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: kaartspel-app:latest
    container_name: kaartspel_app
    environment:
      - POSTGRES_URL=postgresql://postgres:postgres@postgres:5432/postgres
      - AUTH_SECRET=fa51e1066130719feacc6d6d93ac2b73182eeaa7ff40c3c45c2a5063865c258f
      - NODE_ENV=production
    ports:
      - "3000:3000"
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
